/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef RUNTIMEBROKER_PRIVATE_H
#define RUNTIMEBROKER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"10.0.19041.746"
#define VER_MAJOR	10
#define VER_MINOR	0
#define VER_RELEASE	19041
#define VER_BUILD	746
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	""
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	""

#endif /*RUNTIMEBROKER_PRIVATE_H*/
